---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.NAME }}-svc-cip"
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  type: ClusterIP
  selector:
    environment: "{{ .Values.NAMESPACE }}"
    app: "{{ .Values.APP }}"
    microservice: "{{ .Values.MICROSERVICE }}"
  ports:
  - name: default
    port: 3000
    targetPort: 3000
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.NAME }}-svc-np"
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  type: NodePort
  selector:
    environment: "{{ .Values.NAMESPACE }}"
    app: "{{ .Values.APP }}"
    microservice: "{{ .Values.MICROSERVICE }}"
  ports:
  - name: default
    port: 3000
    targetPort: 3000
    nodePort: 30008
    protocol: TCP